name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes Readme.md
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'Readme.md'
        destination_repo: 'rahgadda/rahgadda'
        destination_folder: '/'
        user_email: 'gaddam.rahul@gmail.com'
        user_name: 'rahgadda'
        commit_message: 'Auto Commit from rahgadda.github.io repo update'
